# vim: set tabstop=4 shiftwidth=4 noexpandtab
# ================================================================
# Filename:		Makefile
#
# Description:	Makefile for building and running tests of pmake
#
# Author(s):	Bill McSpadden (bill@riscv.org)
#
# Revision:		See git log
#
# ================================================================
#
include ./Makefile.header
include ${TEST_DIR_PATH}/lib/pmake/Makefile.common.top


include ${TEST_DIR_PATH}/lib/pmake/Makefile.common.bottom

